name: MobPluginPM
main: jasonwynn10\VanillaEntityAI\EntityAI
version: 0.0.9-alpha
api:
- 3.0.0
mcpe-protocols:
- 448
description: "A plugin for vanilla-like mob AI"
author: "jasonwynn10"
load: STARTUP
softdepend:
- PureEntitiesX
