name: MobPluginPM
main: jasonwynn10\VanillaEntityAI\EntityAI
version: 2.0.0
api:
- 4.0.0
mcpe-protocols:
- 448
description: "A plugin for vanilla-like mob AI"
author: "jasonwynn10"
load: STARTUP
softdepend:
- PureEntitiesX
