name: MobPluginPM
main: jasonwynn10\VanillaEntityAI\EntityAI
version: 0.0.9-alpha
api:
- 4.0.0
mcpe-protocols:
- 471
description: "A plugin for vanilla-like mob AI, based on Altays AI"
author: "TuranicTeam"
load: STARTUP
